# cargo-about is really only ever intended to run on the "normal" tier-1 targets
targets = [
    { triple = "x86_64-unknown-linux-gnu" },
    { triple = "x86_64-unknown-linux-musl" },
    { triple = "x86_64-apple-darwin" },
    { triple = "x86_64-pc-windows-msvc" },
]

[advisories]
ignore = [
    "RUSTSEC-2019-0031",
]

[bans]
multiple-versions = "deny"
deny = [
    # You can never be too sure
    { name = "openssl-sys" },
]
skip = [
    # clap uses old ansi-term
    { name = "ansi_term", version = "0.11.0" },
    # old mio :(
    { name = "winapi", version = "=0.2.8" },
]

[licenses]
unlicensed = "deny"
allow-osi-fsf-free = "neither"
copyleft = "deny"
# We want really high confidence when inferring licenses from text
confidence-threshold = 0.93
allow = [
    "Apache-2.0",
    "MIT",
]
exceptions = [
    { allow = ["MPL-2.0"], name = "webpki-roots" },
    { allow = ["ISC"], name = "untrusted" },
]

[sources]
unknown-git = "allow"
